### ISSUE TITLE
 JSON editing use cases

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/MiCall-Lite#12]
The purpose of enumerating plausible use cases is to have some basis for designing the user interface for editing JSON files.

## Use cases
1. User wants to **add** an additional seed reference sequence to an existing project.
2.

**Comment by rng64** [comment]
## Use cases


1. User wants to **view** data of existing project.
2. User wants to **add** additional project.
        a. User wants to **add** additional seed reference to an existing project.
 	b. User wants to **add** coordinate region to an existing project.
	c. User wants to **add** seed region to an existing project.
3. User wants to **change** existing project data.
        a. User wants to **change** seed reference of an existing project.
 	b. User wants to **change** coordinate region data.
 	c. User wants to **change** seed region data.
        d. User wants to **change** description.
4. User wants to **delete** exist project data.
        a. User wants to **delete** seed reference of an existing project.
        b. User wants to **delete** coordinate region data.
        c. User wants to **delete** seed region data.
