### ISSUE TITLE
.csv files generated by Micall do not contain data other than the headings

### ISSUE THREAD

**Issue by rng64** [PoonLab/MiCall-Lite#23]
When running micall, the .csv files generated do not contain data other than the headings. Below is a test case consisting of .fastq files with 1000 lines.
```terminal
ng64@Arsibalt:~$ micall -u /data/temp1.fastq /data/temp2.fastq
MiCall-Lite running sample temp1...
  Preliminary map
  Iterative remap
  Generating alignment file
  Generating count files

**Comment by ArtPoon** [comment]
FASTQ files did not actually contain any influenza virus sequences.  Closing.
