### ISSUE TITLE
Please Tag a Release to Facilitate Integration to Bioconda

### ISSUE THREAD

**Issue by dfornika** [PoonLab/MiCall-Lite#24]
Hi @ArtPoon, would you be able to tag a new release on this repo?

I've submitted a pull request to include MiCall-Lite in the bioconda project. If it can be included, that may make installation easier (#10) and also facilitate integration with tools like Galaxy and Docker.

I didn't realize until I had submitted my pull-request that the most recent tag on this repo was created in July of 2016. 

https://github.com/bioconda/bioconda-recipes/pull/14122

**Comment by ArtPoon** [comment]
Hi @dfornika.  Thanks for your interest and efforts.  I don't mind tagging a new release on the current master branch, although the new GUI for editing the reference sequence JSON file is newly implemented and not yet stable.  I don't know much about bioconda, so could you please explain how making this tag will help with being included?

**Comment by ArtPoon** [comment]
@dfornika - Sorry for the delay, I've been away at a conference all last week.  I've posted a release, let me know if this works for you and thanks for your support!

**Comment by dfornika** [comment]
Hi @ArtPoon, no apologies necessary. I was slow to answer your question about how a tag would help with bioconda integration.

A tag creates a stable snapshot of the codebase that bioconda can use to download & package the code reproducibly. The policy is described [here](https://bioconda.github.io/guidelines.html#stable-urls)

> Ideally, a github repo should have tagged releases that are accessible as tarballs from the “releases” section of the github repo.

Having a 'release tarball' available also makes it simpler to create a checksum for the source code, so an automated download system can check that the file that it downloaded is complete and unmodified. The bioconda guidelines describe 'hashes' (ie. checksums) [here](https://bioconda.github.io/guidelines.html#hashes)
