### ISSUE TITLE
How to with multi-file batch processing

### ISSUE THREAD

**Issue by hihuhu** [PoonLab/MiCall-Lite#29]
I just used this program, but I am not a computer professional, I now have 10 files, I want to dispose of one time, do not want to dispose of one time, what should I do? I tried to run in many terminals at the same time, but I couldn't. I hope the author can give me some advice.

**Comment by ArtPoon** [comment]
Hi @hihuhu!  There are many ways to do batch processing on the command line, such as writing a bash script, but this is usually too complicated for a new user.  I guess the simplest approach would be for me to write a batch script for you to try.  Give me a minute.

**Comment by hihuhu** [comment]
Thank you very much for your help.

**Comment by ArtPoon** [comment]
Ok, I've posted a new Python script as a GitHub gist, which you can access [here](https://gist.github.com/ArtPoon/42b667f300a08149ba796e329cf2a7e3).

To run this script, you just need to provide an absolute or relative path to the directory containing the FASTQ gzip-compressed files that you want to process:
```console
art@orolo:~/git/micall/bin$ python3 batch-micall.py /data/miseq/integrase/
Detected 523 gzipped FASTQ files at /data/miseq/integrase/
/data/miseq/integrase/DR-88-13-2_S180_L001_R1_001.fastq.gz
MiCall-Lite running sample DR-88-13-2_S180_L001_R1_001...
  Preliminary map
  Iterative remap
  Generating alignment file
  Generating count files
/data/miseq/integrase/DR-240-16_S305_L001_R1_001.fastq.gz
MiCall-Lite running sample DR-240-16_S305_L001_R1_001...
  Preliminary map
  Iterative remap
```

**Comment by hihuhu** [comment]
Thank you！
